# Deployment
## "Manages the deployment and scaling of the applications while maintaining 
## the desired state of the application" (GeeksForGeeks)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-volue
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-volume
          PersistentVolumeClaim:
            claimName: jenkins-pvc
           
